sudo: required

language: node_js

services:
  - docker

before_install:
  - docker pull node:9.2.0-alpine
  - docker ps -a

script:
  - ./docker-login.sh $DOCKER_USER $DOCKER_PASS
  - ./build.sh $TRAVIS_BUILD_NUMBER
